/**
 * Esquemas de cada módulo - mapean rutas del frontend a recursos del backend PHP
 * y definen los campos del formulario CRUD.
 */
export interface FieldDef {
  name: string;
  label: string;
  type?: "text" | "number" | "date" | "datetime-local" | "select" | "textarea" | "email" | "tel";
  options?: { value: string; label: string }[];
  required?: boolean;
}

export interface ModuleSchema {
  resource: string;       // backend endpoint segment, e.g. "tesoreria"
  title: string;
  singular: string;       // singular form for buttons ("Nueva cuenta")
  columns: { key: string; label: string; format?: "money" | "date" | "badge" }[];
  fields: FieldDef[];
}

export const moduleSchemas: Record<string, ModuleSchema> = {
  "/finanzas/tesoreria": {
    resource: "tesoreria",
    title: "Tesorería",
    singular: "Cuenta",
    columns: [
      { key: "nombre", label: "Nombre" },
      { key: "banco", label: "Banco" },
      { key: "numero_cuenta", label: "Nº Cuenta" },
      { key: "tipo", label: "Tipo", format: "badge" },
      { key: "moneda", label: "Moneda" },
      { key: "saldo_actual", label: "Saldo", format: "money" },
    ],
    fields: [
      { name: "nombre", label: "Nombre", required: true },
      { name: "banco", label: "Banco" },
      { name: "numero_cuenta", label: "Número de cuenta" },
      { name: "tipo", label: "Tipo", type: "select", options: [
        { value: "corriente", label: "Corriente" },
        { value: "ahorros", label: "Ahorros" },
        { value: "caja", label: "Caja" },
        { value: "tarjeta", label: "Tarjeta" },
      ]},
      { name: "moneda", label: "Moneda", type: "select", options: [
        { value: "DOP", label: "DOP - Peso Dominicano" },
        { value: "USD", label: "USD - Dólar" },
        { value: "EUR", label: "EUR - Euro" },
      ]},
      { name: "saldo_inicial", label: "Saldo inicial", type: "number" },
      { name: "saldo_actual", label: "Saldo actual", type: "number" },
    ],
  },
  "/finanzas/cxc": {
    resource: "cxc",
    title: "Cuentas por Cobrar",
    singular: "Factura",
    columns: [
      { key: "numero", label: "Número" },
      { key: "ncf", label: "NCF" },
      { key: "fecha", label: "Fecha", format: "date" },
      { key: "fecha_vencimiento", label: "Vencimiento", format: "date" },
      { key: "total", label: "Total", format: "money" },
      { key: "balance", label: "Balance", format: "money" },
      { key: "estado", label: "Estado", format: "badge" },
    ],
    fields: [
      { name: "numero", label: "Número" },
      { name: "ncf", label: "NCF" },
      { name: "tipo_ncf", label: "Tipo NCF", type: "select", options: [
        { value: "01", label: "01 - Crédito Fiscal" },
        { value: "02", label: "02 - Consumo" },
        { value: "14", label: "14 - Régimen Especial" },
        { value: "15", label: "15 - Gubernamental" },
      ]},
      { name: "cliente_id", label: "Cliente ID", type: "number", required: true },
      { name: "fecha", label: "Fecha", type: "date", required: true },
      { name: "fecha_vencimiento", label: "Fecha vencimiento", type: "date" },
      { name: "subtotal", label: "Subtotal", type: "number" },
      { name: "itbis", label: "ITBIS (18%)", type: "number" },
      { name: "total", label: "Total", type: "number", required: true },
      { name: "estado", label: "Estado", type: "select", options: [
        { value: "pendiente", label: "Pendiente" },
        { value: "pagada", label: "Pagada" },
        { value: "vencida", label: "Vencida" },
        { value: "anulada", label: "Anulada" },
      ]},
      { name: "notas", label: "Notas", type: "textarea" },
    ],
  },
  "/finanzas/cxp": {
    resource: "cxp",
    title: "Cuentas por Pagar",
    singular: "Factura compra",
    columns: [
      { key: "numero", label: "Número" },
      { key: "ncf_proveedor", label: "NCF Prov." },
      { key: "fecha", label: "Fecha", format: "date" },
      { key: "total", label: "Total", format: "money" },
      { key: "balance", label: "Balance", format: "money" },
      { key: "estado", label: "Estado", format: "badge" },
    ],
    fields: [
      { name: "numero", label: "Número" },
      { name: "ncf_proveedor", label: "NCF del proveedor" },
      { name: "proveedor_id", label: "Proveedor ID", type: "number", required: true },
      { name: "fecha", label: "Fecha", type: "date", required: true },
      { name: "fecha_vencimiento", label: "Vencimiento", type: "date" },
      { name: "subtotal", label: "Subtotal", type: "number" },
      { name: "itbis", label: "ITBIS", type: "number" },
      { name: "total", label: "Total", type: "number", required: true },
      { name: "estado", label: "Estado", type: "select", options: [
        { value: "pendiente", label: "Pendiente" },
        { value: "pagada", label: "Pagada" },
        { value: "vencida", label: "Vencida" },
      ]},
      { name: "notas", label: "Notas", type: "textarea" },
    ],
  },
  "/finanzas/contabilidad": {
    resource: "contabilidad",
    title: "Contabilidad - Plan de Cuentas",
    singular: "Cuenta contable",
    columns: [
      { key: "codigo", label: "Código" },
      { key: "nombre", label: "Nombre" },
      { key: "tipo", label: "Tipo", format: "badge" },
      { key: "naturaleza", label: "Naturaleza" },
    ],
    fields: [
      { name: "codigo", label: "Código", required: true },
      { name: "nombre", label: "Nombre", required: true },
      { name: "tipo", label: "Tipo", type: "select", required: true, options: [
        { value: "activo", label: "Activo" },
        { value: "pasivo", label: "Pasivo" },
        { value: "patrimonio", label: "Patrimonio" },
        { value: "ingreso", label: "Ingreso" },
        { value: "gasto", label: "Gasto" },
        { value: "costo", label: "Costo" },
      ]},
      { name: "naturaleza", label: "Naturaleza", type: "select", required: true, options: [
        { value: "deudora", label: "Deudora" },
        { value: "acreedora", label: "Acreedora" },
      ]},
    ],
  },
  "/finanzas/presupuestos": {
    resource: "presupuestos",
    title: "Presupuestos",
    singular: "Presupuesto",
    columns: [
      { key: "nombre", label: "Nombre" },
      { key: "anio", label: "Año" },
      { key: "mes", label: "Mes" },
      { key: "categoria", label: "Categoría" },
      { key: "monto_presupuestado", label: "Presupuestado", format: "money" },
      { key: "monto_ejecutado", label: "Ejecutado", format: "money" },
    ],
    fields: [
      { name: "nombre", label: "Nombre", required: true },
      { name: "anio", label: "Año", type: "number", required: true },
      { name: "mes", label: "Mes (1-12)", type: "number" },
      { name: "categoria", label: "Categoría" },
      { name: "monto_presupuestado", label: "Monto presupuestado", type: "number", required: true },
      { name: "monto_ejecutado", label: "Monto ejecutado", type: "number" },
      { name: "notas", label: "Notas", type: "textarea" },
    ],
  },
  "/finanzas/impuestos": {
    resource: "impuestos",
    title: "Impuestos DGII",
    singular: "Declaración",
    columns: [
      { key: "tipo", label: "Tipo", format: "badge" },
      { key: "periodo", label: "Período" },
      { key: "monto_a_pagar", label: "A pagar", format: "money" },
      { key: "fecha_vencimiento", label: "Vence", format: "date" },
      { key: "estado", label: "Estado", format: "badge" },
    ],
    fields: [
      { name: "tipo", label: "Tipo declaración", type: "select", required: true, options: [
        { value: "IT-1", label: "IT-1 (ITBIS)" },
        { value: "IR-3", label: "IR-3 (Retenciones)" },
        { value: "IR-17", label: "IR-17 (Otras retenciones)" },
        { value: "IR-4", label: "IR-4 (ISR Anual)" },
        { value: "606", label: "606 - Compras" },
        { value: "607", label: "607 - Ventas" },
        { value: "608", label: "608 - NCF Anulados" },
        { value: "609", label: "609 - Pagos al exterior" },
      ]},
      { name: "periodo", label: "Período (YYYY-MM)", required: true },
      { name: "monto_a_pagar", label: "Monto a pagar", type: "number" },
      { name: "fecha_presentacion", label: "Fecha presentación", type: "date" },
      { name: "fecha_vencimiento", label: "Fecha vencimiento", type: "date" },
      { name: "estado", label: "Estado", type: "select", options: [
        { value: "borrador", label: "Borrador" },
        { value: "presentada", label: "Presentada" },
        { value: "pagada", label: "Pagada" },
        { value: "vencida", label: "Vencida" },
      ]},
      { name: "notas", label: "Notas", type: "textarea" },
    ],
  },
  "/finanzas/activos": {
    resource: "activos",
    title: "Activos Fijos",
    singular: "Activo",
    columns: [
      { key: "codigo", label: "Código" },
      { key: "nombre", label: "Nombre" },
      { key: "categoria", label: "Categoría" },
      { key: "valor_adquisicion", label: "Valor", format: "money" },
      { key: "valor_libros", label: "Valor libros", format: "money" },
      { key: "estado", label: "Estado", format: "badge" },
    ],
    fields: [
      { name: "codigo", label: "Código" },
      { name: "nombre", label: "Nombre", required: true },
      { name: "categoria", label: "Categoría" },
      { name: "fecha_adquisicion", label: "Fecha adquisición", type: "date" },
      { name: "valor_adquisicion", label: "Valor adquisición", type: "number" },
      { name: "vida_util_anios", label: "Vida útil (años)", type: "number" },
      { name: "depreciacion_acumulada", label: "Depreciación acumulada", type: "number" },
      { name: "valor_libros", label: "Valor en libros", type: "number" },
      { name: "ubicacion", label: "Ubicación" },
      { name: "estado", label: "Estado", type: "select", options: [
        { value: "activo", label: "Activo" },
        { value: "mantenimiento", label: "Mantenimiento" },
        { value: "baja", label: "Baja" },
        { value: "venta", label: "Venta" },
      ]},
    ],
  },
  "/finanzas/analisis": {
    resource: "dashboard",
    title: "Análisis Financiero",
    singular: "",
    columns: [],
    fields: [],
  },

  // ============ RRHH ============
  "/rrhh/reclutamiento": {
    resource: "reclutamiento",
    title: "Reclutamiento",
    singular: "Vacante",
    columns: [
      { key: "titulo", label: "Vacante" },
      { key: "departamento", label: "Departamento" },
      { key: "salario_min", label: "Salario mín.", format: "money" },
      { key: "salario_max", label: "Salario máx.", format: "money" },
      { key: "estado", label: "Estado", format: "badge" },
      { key: "fecha_publicacion", label: "Publicada", format: "date" },
    ],
    fields: [
      { name: "titulo", label: "Título de la vacante", required: true },
      { name: "departamento", label: "Departamento" },
      { name: "descripcion", label: "Descripción", type: "textarea" },
      { name: "requisitos", label: "Requisitos", type: "textarea" },
      { name: "salario_min", label: "Salario mínimo", type: "number" },
      { name: "salario_max", label: "Salario máximo", type: "number" },
      { name: "fecha_publicacion", label: "Fecha publicación", type: "date" },
      { name: "fecha_cierre", label: "Fecha cierre", type: "date" },
      { name: "estado", label: "Estado", type: "select", options: [
        { value: "abierta", label: "Abierta" },
        { value: "en_proceso", label: "En proceso" },
        { value: "cerrada", label: "Cerrada" },
        { value: "cancelada", label: "Cancelada" },
      ]},
    ],
  },
  "/rrhh/nomina": {
    resource: "nomina",
    title: "Nómina",
    singular: "Nómina",
    columns: [
      { key: "periodo", label: "Período" },
      { key: "tipo", label: "Tipo", format: "badge" },
      { key: "fecha_pago", label: "Fecha pago", format: "date" },
      { key: "total_bruto", label: "Bruto", format: "money" },
      { key: "total_deducciones", label: "Deducciones", format: "money" },
      { key: "total_neto", label: "Neto", format: "money" },
      { key: "estado", label: "Estado", format: "badge" },
    ],
    fields: [
      { name: "periodo", label: "Período (YYYY-MM)", required: true },
      { name: "tipo", label: "Tipo", type: "select", required: true, options: [
        { value: "mensual", label: "Mensual" },
        { value: "quincenal", label: "Quincenal" },
        { value: "regalia", label: "Regalía Pascual" },
        { value: "vacaciones", label: "Vacaciones" },
        { value: "liquidacion", label: "Liquidación" },
      ]},
      { name: "fecha_inicio", label: "Fecha inicio", type: "date", required: true },
      { name: "fecha_fin", label: "Fecha fin", type: "date", required: true },
      { name: "fecha_pago", label: "Fecha pago", type: "date" },
    ],
  },
  "/rrhh/asistencia": {
    resource: "asistencia",
    title: "Asistencia",
    singular: "Registro",
    columns: [
      { key: "empleado_id", label: "Empleado" },
      { key: "fecha", label: "Fecha", format: "date" },
      { key: "hora_entrada", label: "Entrada" },
      { key: "hora_salida", label: "Salida" },
      { key: "horas_trabajadas", label: "Horas" },
      { key: "tipo", label: "Tipo", format: "badge" },
    ],
    fields: [
      { name: "empleado_id", label: "Empleado ID", type: "number", required: true },
      { name: "fecha", label: "Fecha", type: "date", required: true },
      { name: "hora_entrada", label: "Hora entrada", type: "text" },
      { name: "hora_salida", label: "Hora salida", type: "text" },
      { name: "horas_trabajadas", label: "Horas trabajadas", type: "number" },
      { name: "horas_extras", label: "Horas extras", type: "number" },
      { name: "tipo", label: "Tipo", type: "select", options: [
        { value: "presente", label: "Presente" },
        { value: "ausente", label: "Ausente" },
        { value: "tardanza", label: "Tardanza" },
        { value: "permiso", label: "Permiso" },
        { value: "licencia", label: "Licencia" },
        { value: "feriado", label: "Feriado" },
      ]},
      { name: "notas", label: "Notas", type: "textarea" },
    ],
  },
  "/rrhh/vacaciones": {
    resource: "vacaciones",
    title: "Vacaciones y Permisos",
    singular: "Solicitud",
    columns: [
      { key: "empleado_id", label: "Empleado" },
      { key: "fecha_inicio", label: "Desde", format: "date" },
      { key: "fecha_fin", label: "Hasta", format: "date" },
      { key: "dias_solicitados", label: "Días" },
      { key: "monto_pagado", label: "Monto", format: "money" },
      { key: "estado", label: "Estado", format: "badge" },
    ],
    fields: [
      { name: "empleado_id", label: "Empleado ID", type: "number", required: true },
      { name: "fecha_inicio", label: "Fecha inicio", type: "date", required: true },
      { name: "fecha_fin", label: "Fecha fin", type: "date", required: true },
      { name: "dias_solicitados", label: "Días solicitados (mín. 14 según Ley 16-92)", type: "number", required: true },
      { name: "dias_pagados", label: "Días pagados", type: "number" },
      { name: "monto_pagado", label: "Monto pagado", type: "number" },
      { name: "estado", label: "Estado", type: "select", options: [
        { value: "solicitada", label: "Solicitada" },
        { value: "aprobada", label: "Aprobada" },
        { value: "rechazada", label: "Rechazada" },
        { value: "disfrutando", label: "Disfrutando" },
        { value: "completada", label: "Completada" },
      ]},
      { name: "motivo", label: "Motivo", type: "textarea" },
    ],
  },
  "/rrhh/desempeno": {
    resource: "desempeno",
    title: "Evaluaciones de Desempeño",
    singular: "Evaluación",
    columns: [
      { key: "empleado_id", label: "Empleado" },
      { key: "periodo", label: "Período" },
      { key: "fecha", label: "Fecha", format: "date" },
      { key: "promedio", label: "Promedio" },
    ],
    fields: [
      { name: "empleado_id", label: "Empleado ID", type: "number", required: true },
      { name: "evaluador_id", label: "Evaluador ID", type: "number" },
      { name: "periodo", label: "Período" },
      { name: "fecha", label: "Fecha", type: "date" },
      { name: "puntualidad", label: "Puntualidad (1-100)", type: "number" },
      { name: "productividad", label: "Productividad (1-100)", type: "number" },
      { name: "calidad", label: "Calidad (1-100)", type: "number" },
      { name: "trabajo_equipo", label: "Trabajo en equipo (1-100)", type: "number" },
      { name: "iniciativa", label: "Iniciativa (1-100)", type: "number" },
      { name: "promedio", label: "Promedio", type: "number" },
      { name: "comentarios", label: "Comentarios", type: "textarea" },
      { name: "plan_mejora", label: "Plan de mejora", type: "textarea" },
    ],
  },
  "/rrhh/capacitacion": {
    resource: "capacitacion",
    title: "Capacitaciones",
    singular: "Capacitación",
    columns: [
      { key: "titulo", label: "Título" },
      { key: "instructor", label: "Instructor" },
      { key: "modalidad", label: "Modalidad" },
      { key: "fecha_inicio", label: "Inicio", format: "date" },
      { key: "horas", label: "Horas" },
      { key: "estado", label: "Estado", format: "badge" },
    ],
    fields: [
      { name: "titulo", label: "Título", required: true },
      { name: "descripcion", label: "Descripción", type: "textarea" },
      { name: "instructor", label: "Instructor" },
      { name: "modalidad", label: "Modalidad", type: "select", options: [
        { value: "presencial", label: "Presencial" },
        { value: "virtual", label: "Virtual" },
        { value: "hibrida", label: "Híbrida" },
      ]},
      { name: "fecha_inicio", label: "Fecha inicio", type: "date" },
      { name: "fecha_fin", label: "Fecha fin", type: "date" },
      { name: "horas", label: "Horas", type: "number" },
      { name: "costo", label: "Costo", type: "number" },
      { name: "estado", label: "Estado", type: "select", options: [
        { value: "programada", label: "Programada" },
        { value: "en_curso", label: "En curso" },
        { value: "completada", label: "Completada" },
        { value: "cancelada", label: "Cancelada" },
      ]},
    ],
  },
  "/rrhh/beneficios": {
    resource: "beneficios",
    title: "Beneficios",
    singular: "Beneficio",
    columns: [
      { key: "nombre", label: "Nombre" },
      { key: "tipo", label: "Tipo", format: "badge" },
      { key: "costo_empresa", label: "Costo empresa", format: "money" },
      { key: "costo_empleado", label: "Costo empleado", format: "money" },
    ],
    fields: [
      { name: "nombre", label: "Nombre", required: true },
      { name: "tipo", label: "Tipo", type: "select", options: [
        { value: "seguro_salud", label: "Seguro de salud" },
        { value: "plan_dental", label: "Plan dental" },
        { value: "bono", label: "Bono" },
        { value: "transporte", label: "Transporte" },
        { value: "alimentacion", label: "Alimentación" },
        { value: "educacion", label: "Educación" },
        { value: "otro", label: "Otro" },
      ]},
      { name: "descripcion", label: "Descripción", type: "textarea" },
      { name: "costo_empresa", label: "Costo empresa", type: "number" },
      { name: "costo_empleado", label: "Costo empleado", type: "number" },
    ],
  },
  "/rrhh/organigrama": {
    resource: "empleados",
    title: "Organigrama",
    singular: "Empleado",
    columns: [
      { key: "codigo", label: "Código" },
      { key: "nombre", label: "Nombre" },
      { key: "departamento", label: "Departamento" },
      { key: "puesto", label: "Puesto" },
      { key: "supervisor_id", label: "Supervisor" },
    ],
    fields: [
      { name: "codigo", label: "Código" },
      { name: "nombre", label: "Nombre", required: true },
      { name: "departamento", label: "Departamento" },
      { name: "puesto", label: "Puesto" },
      { name: "supervisor_id", label: "Supervisor ID", type: "number" },
    ],
  },
  "/rrhh/clima": {
    resource: "notificaciones",
    title: "Clima Laboral - Encuestas",
    singular: "Encuesta",
    columns: [
      { key: "titulo", label: "Título" },
      { key: "tipo", label: "Tipo", format: "badge" },
      { key: "created_at", label: "Fecha", format: "date" },
    ],
    fields: [
      { name: "titulo", label: "Título", required: true },
      { name: "mensaje", label: "Pregunta / mensaje", type: "textarea", required: true },
      { name: "tipo", label: "Tipo", type: "select", options: [
        { value: "info", label: "Información" },
        { value: "exito", label: "Éxito" },
        { value: "advertencia", label: "Advertencia" },
      ]},
    ],
  },

  // ============ Herramientas ============
  "/tools/importar": {
    resource: "auditoria",
    title: "Importar Datos",
    singular: "Importación",
    columns: [
      { key: "accion", label: "Acción" },
      { key: "tabla", label: "Tabla destino" },
      { key: "created_at", label: "Fecha", format: "date" },
    ],
    fields: [
      { name: "accion", label: "Tipo de importación", type: "select", required: true, options: [
        { value: "import_clientes", label: "Clientes (Excel)" },
        { value: "import_productos", label: "Productos (Excel)" },
        { value: "import_facturas", label: "Facturas (CSV)" },
        { value: "import_empleados", label: "Empleados (Excel)" },
      ]},
      { name: "tabla", label: "Tabla destino" },
      { name: "datos_despues", label: "Notas / archivo", type: "textarea" },
    ],
  },
  "/tools/exportar": {
    resource: "auditoria",
    title: "Exportar / Backups",
    singular: "Exportación",
    columns: [
      { key: "accion", label: "Acción" },
      { key: "created_at", label: "Fecha", format: "date" },
    ],
    fields: [
      { name: "accion", label: "Tipo de export", type: "select", required: true, options: [
        { value: "backup_full", label: "Backup completo BD" },
        { value: "export_excel", label: "Exportar a Excel" },
        { value: "export_pdf", label: "Exportar a PDF" },
        { value: "export_606", label: "Reporte 606 DGII" },
        { value: "export_607", label: "Reporte 607 DGII" },
      ]},
      { name: "datos_despues", label: "Detalles", type: "textarea" },
    ],
  },
  "/tools/automatizacion": {
    resource: "integraciones",
    title: "Automatizaciones",
    singular: "Flujo",
    columns: [
      { key: "nombre", label: "Nombre" },
      { key: "tipo", label: "Tipo" },
      { key: "activa", label: "Activa", format: "badge" },
      { key: "ultima_sincronizacion", label: "Última ejecución", format: "date" },
    ],
    fields: [
      { name: "nombre", label: "Nombre del flujo", required: true },
      { name: "tipo", label: "Tipo", type: "select", options: [
        { value: "recordatorio_factura", label: "Recordatorio de factura vencida" },
        { value: "calculo_nomina", label: "Cálculo automático de nómina" },
        { value: "alerta_stock", label: "Alerta de stock mínimo" },
        { value: "backup_diario", label: "Backup diario" },
        { value: "regalia_diciembre", label: "Regalía Pascual (Diciembre)" },
      ]},
      { name: "config", label: "Configuración JSON", type: "textarea" },
      { name: "activa", label: "Activa", type: "select", options: [
        { value: "1", label: "Sí" }, { value: "0", label: "No" },
      ]},
    ],
  },
  "/tools/integraciones": {
    resource: "integraciones",
    title: "Integraciones Externas",
    singular: "Integración",
    columns: [
      { key: "nombre", label: "Servicio" },
      { key: "tipo", label: "Tipo" },
      { key: "activa", label: "Activa", format: "badge" },
    ],
    fields: [
      { name: "nombre", label: "Nombre del servicio", required: true },
      { name: "tipo", label: "Tipo", type: "select", options: [
        { value: "dgii", label: "DGII e-CF" },
        { value: "banco", label: "Banco / pasarela" },
        { value: "whatsapp", label: "WhatsApp Business" },
        { value: "google", label: "Google Workspace" },
        { value: "office365", label: "Microsoft 365" },
        { value: "tss", label: "TSS / SISALRIL" },
      ]},
      { name: "config", label: "Credenciales / config", type: "textarea" },
      { name: "activa", label: "Activa", type: "select", options: [
        { value: "1", label: "Sí" }, { value: "0", label: "No" },
      ]},
    ],
  },
  "/tools/auditoria": {
    resource: "auditoria",
    title: "Auditoría del Sistema",
    singular: "Evento",
    columns: [
      { key: "usuario_id", label: "Usuario" },
      { key: "accion", label: "Acción" },
      { key: "tabla", label: "Tabla" },
      { key: "ip", label: "IP" },
      { key: "created_at", label: "Fecha", format: "date" },
    ],
    fields: [
      { name: "usuario_id", label: "Usuario ID", type: "number" },
      { name: "accion", label: "Acción", required: true },
      { name: "tabla", label: "Tabla" },
      { name: "registro_id", label: "Registro ID", type: "number" },
      { name: "ip", label: "IP" },
      { name: "user_agent", label: "User agent" },
    ],
  },
  "/tools/permisos": {
    resource: "usuarios",
    title: "Roles y Permisos",
    singular: "Usuario",
    columns: [
      { key: "nombre", label: "Nombre" },
      { key: "email", label: "Email" },
      { key: "rol", label: "Rol", format: "badge" },
      { key: "departamento", label: "Departamento" },
      { key: "activo", label: "Activo", format: "badge" },
    ],
    fields: [
      { name: "nombre", label: "Nombre", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "rol", label: "Rol", type: "select", required: true, options: [
        { value: "admin", label: "Administrador" },
        { value: "manager", label: "Manager" },
        { value: "contador", label: "Contador" },
        { value: "rrhh", label: "RRHH" },
        { value: "vendedor", label: "Vendedor" },
        { value: "viewer", label: "Solo lectura" },
      ]},
      { name: "telefono", label: "Teléfono", type: "tel" },
      { name: "departamento", label: "Departamento" },
      { name: "activo", label: "Activo", type: "select", options: [
        { value: "1", label: "Sí" }, { value: "0", label: "No" },
      ]},
    ],
  },
  "/tools/tareas": {
    resource: "tareas",
    title: "Tareas y Proyectos",
    singular: "Tarea",
    columns: [
      { key: "titulo", label: "Tarea" },
      { key: "asignado_a", label: "Asignado a" },
      { key: "prioridad", label: "Prioridad", format: "badge" },
      { key: "fecha_vencimiento", label: "Vence", format: "date" },
      { key: "estado", label: "Estado", format: "badge" },
    ],
    fields: [
      { name: "titulo", label: "Título", required: true },
      { name: "descripcion", label: "Descripción", type: "textarea" },
      { name: "asignado_a", label: "Asignado a (usuario ID)", type: "number" },
      { name: "prioridad", label: "Prioridad", type: "select", options: [
        { value: "baja", label: "Baja" },
        { value: "media", label: "Media" },
        { value: "alta", label: "Alta" },
        { value: "urgente", label: "Urgente" },
      ]},
      { name: "estado", label: "Estado", type: "select", options: [
        { value: "pendiente", label: "Pendiente" },
        { value: "en_progreso", label: "En progreso" },
        { value: "completada", label: "Completada" },
        { value: "cancelada", label: "Cancelada" },
      ]},
      { name: "fecha_vencimiento", label: "Fecha vencimiento", type: "date" },
    ],
  },
  "/tools/calendario": {
    resource: "calendario",
    title: "Calendario",
    singular: "Evento",
    columns: [
      { key: "titulo", label: "Evento" },
      { key: "fecha_inicio", label: "Inicio", format: "date" },
      { key: "fecha_fin", label: "Fin", format: "date" },
      { key: "tipo", label: "Tipo" },
    ],
    fields: [
      { name: "titulo", label: "Título", required: true },
      { name: "descripcion", label: "Descripción", type: "textarea" },
      { name: "fecha_inicio", label: "Fecha inicio", type: "datetime-local", required: true },
      { name: "fecha_fin", label: "Fecha fin", type: "datetime-local" },
      { name: "tipo", label: "Tipo" },
      { name: "color", label: "Color (hex)" },
    ],
  },
  "/tools/notificaciones": {
    resource: "notificaciones",
    title: "Centro de Notificaciones",
    singular: "Notificación",
    columns: [
      { key: "titulo", label: "Título" },
      { key: "tipo", label: "Tipo", format: "badge" },
      { key: "leida", label: "Leída", format: "badge" },
      { key: "created_at", label: "Fecha", format: "date" },
    ],
    fields: [
      { name: "usuario_id", label: "Usuario ID", type: "number" },
      { name: "titulo", label: "Título", required: true },
      { name: "mensaje", label: "Mensaje", type: "textarea", required: true },
      { name: "tipo", label: "Tipo", type: "select", options: [
        { value: "info", label: "Info" },
        { value: "exito", label: "Éxito" },
        { value: "advertencia", label: "Advertencia" },
        { value: "error", label: "Error" },
      ]},
      { name: "url", label: "URL relacionada" },
    ],
  },
};
